In [1]:
from airflow.sdk import dag, task
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.standard.operators.python import PythonOperator
from airflow.providers.standard.operators.empty import EmptyOperator
from airflow.providers.standard.operators.bash import BashOperator
from airflow.sdk import Param
from airflow.sdk.definitions.param import ParamsDict
from sqlalchemy import create_engine, VARCHAR, Integer,Date, inspect
import os
import pandas as pd
from datetime import datetime
import zipfile
import numpy as np
import requests
from datetime import datetime
from pathlib import Path
import shutil
import boto3
from botocore.config import Config

C:\Users\Nelio\AppData\Roaming\Python\Python313\site-packages\airflow\__init__.py:45: RuntimeWarning: Airflow currently can be run on POSIX-compliant Operating Systems. For development, it is regularly tested on fairly modern Linux Distros and recent versions of macOS. On Windows you can run it via WSL2 (Windows Subsystem for Linux 2) or via Linux Containers. The work to add Windows support is tracked via https://github.com/apache/airflow/issues/10388, but it is not a high priority.
  warnings.warn(
2026-04-24T11:13:45.503312Z [info     ] setup plugin alembic.autogenerate.schemas [alembic.runtime.plugins] loc=plugins.py:37
2026-04-24T11:13:45.510949Z [info     ] setup plugin alembic.autogenerate.tables [alembic.runtime.plugins] loc=plugins.py:37
2026-04-24T11:13:45.517173Z [info     ] setup plugin alembic.autogenerate.types [alembic.runtime.plugins] loc=plugins.py:37
2026-04-24T11:13:45.522912Z [info     ] setup plugin alembic.autogenerate.constraints [alembic.runtime.plugins] loc=plugins.py:37
2026-04-24T11:13:45.528432Z [info     ] setup plugin alembic.autogenerate.defaults [alembic.runtime.plugins] loc=plugins.py:37
2026-04-24T11:13:45.535008Z [info     ] setup plugin alembic.autogenerate.comments [alembic.runtime.plugins] loc=plugins.py:37
2026-04-24T11:13:47.538935Z [info     ] NumExpr defaulting to 12 threads. [numexpr.utils] loc=utils.py:161

C:\Users\Nelio\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22 UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).

In [ ]:
# def turnos (file_csv):
#     # engine = create_engine(f"postgresql+psycopg2://{USER}:{PASSWORD}@db:5432/eleicao_RR")
#     # dfs = []
#     colunas_leitura =[
#         'dt_geracao', 'hh_geracao', 'ano_eleicao', 'cd_tipo_eleicao',
#        'nm_tipo_eleicao', 'cd_pleito', 'dt_pleito', 'nr_turno', 'cd_eleicao',
#        'ds_eleicao', 'sg_uf', 'cd_municipio', 'nm_municipio', 'nr_zona',
#        'nr_secao', 'nr_local_votacao', 'cd_cargo_pergunta',
#        'ds_cargo_pergunta', 'nr_partido', 'sg_partido', 'nm_partido',
#        'dt_bu_recebido', 'qt_aptos', 'qt_comparecimento', 'qt_abstencoes',
#        'cd_tipo_urna', 'ds_tipo_urna', 'cd_tipo_votavel', 'ds_tipo_votavel',
#        'nr_votavel', 'nm_votavel', 'qt_votos', 'nr_urna_efetivada',
#        'cd_carga_1_urna_efetivada', 'cd_carga_2_urna_efetivada',
#        'cd_flashcard_urna_efetivada', 'dt_carga_urna_efetivada',
#        'ds_cargo_pergunta_secao', 'ds_agregadas', 'dt_abertura',
#        'dt_encerramento', 'qt_eleitores_biometria_nh', 'dt_emissao_bu',
#        'nr_junta_apuradora', 'nr_turma_apuradora', 'id_zona_secao_municipio',
#        'nm_candidato', 'id_candidato'
#        ]
#     colunas_num = ['nr_turma_apuradora', 'nr_junta_apuradora', 'qt_votos', 'qt_aptos', 'qt_comparecimento', 'qt_abstencoes']
#     colunas_data = ['dt_geracao', 'dt_pleito']
#     colunas_dataHora = ['dt_bu_recebido', 'dt_carga_urna_efetivada', 'dt_abertura', 'dt_encerramento', 'dt_emissao_bu']
#     colunas_hora = ['hr_geracao']
#     for arquivo in os.listdir(file_csv):
#         full_path = os.path.join(file_csv, arquivo)
#         if full_path.endswith('.csv'):
#             df = pd.read_csv(full_path, encoding='latin-1', sep=';',dtype=str,usecols=lambda col: col.strip().lower() in colunas_leitura,nrows=10)
#             for col in colunas_num:
#                 if col in df.columns:
#                     df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
#             for col in colunas_data:
#                 if col in df.columns:
#                     df[col] = pd.to_datetime(df[col], dayfirst=True, format='%d/%m/%Y', errors='coerce').dt.date
#             for col in colunas_hora:
#                 if col in df.columns:
#                     df[col] = pd.to_datetime(df[col], format='%H:%M:%S', errors='coerce').dt.time
#             for col in colunas_dataHora:
#                 if col in df.columns:
#                     df[col] = pd.to_datetime(df[col], dayfirst=True,  format='%d/%m/%Y %H:%M:%S', errors='coerce').dt.date
#             df['ID_ZONA_SECAO_MUNICIPIO'] = df['ANO_ELEICAO'] + df['NR_TURNO'] + df['NR_ZONA'] +  df['NR_SECAO'] +  df['CD_MUNICIPIO']
#             df['NM_CANDIDATO'] = (
#                 df['NM_VOTAVEL']
#                 .fillna('')
#                 .astype(str)
#                 .str.normalize('NFKD')
#                 .str.encode('ascii', 'ignore')
#                 .str.decode('utf-8')
#                 .str.replace(r'[^A-Za-z0-9]+', '', regex=True)
#             )
#             df['ID_CANDIDATO'] = df['ANO_ELEICAO'] + df['NR_TURNO'] +  df['CD_CARGO_PERGUNTA'] + df['CD_MUNICIPIO'] +  df['NR_VOTAVEL'] + df['NM_CANDIDATO']
#             # dfs.append(df)
#             print(f"Carregando o arquivo no banco de archives: {arquivo}")
#             # df.to_sql("resultado", engine, index=False, if_exists='append')
#             print(f"Arquivo Carregado no Bando de archives: {arquivo}")

#     return df

In [17]:
df = turnos(r"C:\Users\Nelio\OneDrive\TRE2026\Archives\RR\turnos\csv")

Carregando o arquivo no banco de archives: bweb_1t_RR_051020221321.csv
Arquivo Carregado no Bando de archives: bweb_1t_RR_051020221321.csv
Carregando o arquivo no banco de archives: bweb_1t_RR_091020241636.csv
Arquivo Carregado no Bando de archives: bweb_1t_RR_091020241636.csv
Carregando o arquivo no banco de archives: bweb_1t_RR_181120201549.csv
Arquivo Carregado no Bando de archives: bweb_1t_RR_181120201549.csv
Carregando o arquivo no banco de archives: bweb_2t_RR_281020241046.csv
Arquivo Carregado no Bando de archives: bweb_2t_RR_281020241046.csv
Carregando o arquivo no banco de archives: bweb_2t_RR_301120201245.csv
Arquivo Carregado no Bando de archives: bweb_2t_RR_301120201245.csv
Carregando o arquivo no banco de archives: bweb_2t_RR_311020221535.csv
Arquivo Carregado no Bando de archives: bweb_2t_RR_311020221535.csv

In [19]:
df

,dt_geracao,hh_geracao,ano_eleicao,cd_tipo_eleicao,nm_tipo_eleicao,cd_pleito,dt_pleito,nr_turno,cd_eleicao,ds_eleicao,...,ds_agregadas,dt_abertura,dt_encerramento,qt_eleitores_biometria_nh,dt_emissao_bu,nr_junta_apuradora,nr_turma_apuradora,id_zona_secao_municipio,nm_candidato,id_candidato
0,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:00:21,7,30/10/2022 16:01:51,-1,-1,20222113018,Branco,202221301895Branco
1,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:00:21,7,30/10/2022 16:01:51,-1,-1,20222113018,LULA,202221301813LULA
2,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:00:21,7,30/10/2022 16:01:51,-1,-1,20222113018,Nulo,202221301896Nulo
3,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:00:21,7,30/10/2022 16:01:51,-1,-1,20222113018,JAIRBOLSONARO,202221301822JAIRBOLSONARO
4,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:03:49,12,30/10/2022 16:06:00,-1,-1,20222123018,Branco,202221301895Branco
5,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:03:49,12,30/10/2022 16:06:00,-1,-1,20222123018,JAIRBOLSONARO,202221301822JAIRBOLSONARO
6,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:03:49,12,30/10/2022 16:06:00,-1,-1,20222123018,LULA,202221301813LULA
7,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:03:49,12,30/10/2022 16:06:00,-1,-1,20222123018,Nulo,202221301896Nulo
8,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:01:11,10,30/10/2022 16:03:01,-1,-1,20222133018,JAIRBOLSONARO,202221301822JAIRBOLSONARO
9,31/10/2022,15:51:19,2022,0,Eleição Ordinária,407,30/10/2022,2,545,Eleição Geral Federal 2022,...,#NULO#,30/10/2022 07:00:01,30/10/2022 16:01:11,10,30/10/2022 16:03:01,-1,-1,20222133018,Branco,202221301895Branco

In [39]:

def turnos (file_csv):
    # engine = create_engine(f"postgresql+psycopg2://{USER}:{PASSWORD}@db:5432/eleicao_RR")
    dfs = []
    colunas_leitura =[
        'dt_geracao', 'hh_geracao', 'ano_eleicao', 'cd_tipo_eleicao',
    'nm_tipo_eleicao', 'cd_pleito', 'dt_pleito', 'nr_turno', 'cd_eleicao',
    'ds_eleicao', 'sg_uf', 'cd_municipio', 'nm_municipio', 'nr_zona',
    'nr_secao', 'nr_local_votacao', 'cd_cargo_pergunta',
    'ds_cargo_pergunta', 'nr_partido', 'sg_partido', 'nm_partido',
    'dt_bu_recebido', 'qt_aptos', 'qt_comparecimento', 'qt_abstencoes',
    'cd_tipo_urna', 'ds_tipo_urna', 'cd_tipo_votavel', 'ds_tipo_votavel',
    'nr_votavel', 'nm_votavel', 'qt_votos', 'nr_urna_efetivada',
    'cd_carga_1_urna_efetivada', 'cd_carga_2_urna_efetivada','sg_ue',
    'cd_flashcard_urna_efetivada', 'dt_carga_urna_efetivada',
    'ds_cargo_pergunta_secao', 'ds_agregadas', 'dt_abertura',
    'dt_encerramento', 'qt_eleitores_biometria_nh', 'dt_emissao_bu',
    'nr_junta_apuradora', 'nr_turma_apuradora', 'id_zona_secao_municipio',
    'nm_candidato', 'id_candidato'
    ]
    colunas_num = ['nr_turma_apuradora', 'nr_junta_apuradora', 'qt_votos', 'qt_aptos', 'qt_comparecimento', 'qt_abstencoes']
    colunas_data = ['dt_geracao', 'dt_pleito']
    colunas_dataHora = ['dt_bu_recebido', 'dt_carga_urna_efetivada', 'dt_abertura', 'dt_encerramento', 'dt_emissao_bu']
    colunas_hora = ['hr_geracao']
    for arquivo in os.listdir(file_csv):
        full_path = os.path.join(file_csv, arquivo)
        if full_path.endswith('.csv'):
            df = pd.read_csv(full_path, encoding='latin-1', sep=';',dtype=str,usecols=lambda col: col.strip().lower() in colunas_leitura)
            df.columns = [col.strip().lower() for col in df.columns]
            for col in colunas_num:
                if col in df.columns:
                    df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')
            for col in colunas_data:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], dayfirst=True, format='%d/%m/%Y', errors='coerce').dt.date
            for col in colunas_hora:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], format='%H:%M:%S', errors='coerce').dt.time
            for col in colunas_dataHora:
                if col in df.columns:
                    df[col] = pd.to_datetime(df[col], dayfirst=True,  format='%d/%m/%Y %H:%M:%S', errors='coerce').dt.date
            df['id_zona_secao_municipio'] = df['ano_eleicao'] + df['nr_turno'] + df['nr_zona'] +  df['nr_secao'] +  df['cd_municipio']
            df['nm_candidato'] = (
                df['nm_votavel']
                .fillna('')
                .astype(str)
                .str.normalize('NFKD')
                .str.encode('ascii', 'ignore')
                .str.decode('utf-8')
                .str.replace(r'[^A-Za-z0-9]+', '', regex=True)
            )
            df['id_candidato'] = df['ano_eleicao'] + df['nr_turno'] +  df['cd_cargo_pergunta'] + df['cd_municipio'] +  df['nr_votavel'] + df['nm_candidato']
            dfs.append(df)
            print(f"Carregando o arquivo no banco de archives: {arquivo}")
            # df.to_sql("resultado", engine, index=False, if_exists='append')
            print(f"Arquivo Carregado no Bando de archives: {arquivo}")

    return df 
# print("Todos os arquivos foram processados e carregados no banco de archives com sucesso!")
df = turnos(r"C:\Users\Nelio\OneDrive\TRE2026\Archives\RR\turnos\csv")
df

Carregando o arquivo no banco de archives: bweb_1t_RR_051020221321.csv
Arquivo Carregado no Bando de archives: bweb_1t_RR_051020221321.csv
Carregando o arquivo no banco de archives: bweb_1t_RR_091020241636.csv
Arquivo Carregado no Bando de archives: bweb_1t_RR_091020241636.csv
Carregando o arquivo no banco de archives: bweb_1t_RR_181120201549.csv
Arquivo Carregado no Bando de archives: bweb_1t_RR_181120201549.csv
Carregando o arquivo no banco de archives: bweb_2t_RR_281020241046.csv
Arquivo Carregado no Bando de archives: bweb_2t_RR_281020241046.csv
Carregando o arquivo no banco de archives: bweb_2t_RR_301120201245.csv
Arquivo Carregado no Bando de archives: bweb_2t_RR_301120201245.csv
Carregando o arquivo no banco de archives: bweb_2t_RR_311020221535.csv
Arquivo Carregado no Bando de archives: bweb_2t_RR_311020221535.csv

,dt_geracao,hh_geracao,ano_eleicao,cd_tipo_eleicao,nm_tipo_eleicao,cd_pleito,dt_pleito,nr_turno,cd_eleicao,ds_eleicao,...,ds_agregadas,dt_abertura,dt_encerramento,qt_eleitores_biometria_nh,dt_emissao_bu,nr_junta_apuradora,nr_turma_apuradora,id_zona_secao_municipio,nm_candidato,id_candidato
0,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,7,2022-10-30,-1,-1,20222113018,Branco,202221301895Branco
1,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,7,2022-10-30,-1,-1,20222113018,LULA,202221301813LULA
2,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,7,2022-10-30,-1,-1,20222113018,Nulo,202221301896Nulo
3,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,7,2022-10-30,-1,-1,20222113018,JAIRBOLSONARO,202221301822JAIRBOLSONARO
4,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,12,2022-10-30,-1,-1,20222123018,Branco,202221301895Branco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4588,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,11,2022-10-30,-1,-1,202228823085,Branco,202221308595Branco
4589,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,8,2022-10-30,-1,-1,202228833085,JAIRBOLSONARO,202221308522JAIRBOLSONARO
4590,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,8,2022-10-30,-1,-1,202228833085,LULA,202221308513LULA
4591,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,8,2022-10-30,-1,-1,202228833085,Nulo,202221308596Nulo
4592,2022-10-31,15:51:19,2022,0,Eleição Ordinária,407,2022-10-30,2,545,Eleição Geral Federal 2022,...,#NULO#,2022-10-30,2022-10-30,8,2022-10-30,-1,-1,202228833085,Branco,202221308595Branco